name: Push Containers to GHCR

on:
  push:
    branches: [main]

jobs:
  push-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app
        run: |
          docker build -t ghcr.io/p3rik/tall-stack-app:latest .
          docker push ghcr.io/p3rik/tall-stack-app:latest

      - name: Push MySQL
        run: |
          docker pull mysql:8.0
          docker tag mysql:8.0 ghcr.io/p3rik/tall-stack-db:latest
          docker push ghcr.io/p3rik/tall-stack-db:latest

      # COmment for push