name: Build and Push Laravel Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Laravel app image
        run: |
          docker compose build
          docker push ghcr.io/p3rik/tall-stack-test

      - name: Push database image
        run: |
          docker pull mysql:8.0
          docker tag mysql:8.0 ghcr.io/p3rik/tall-stack-db:latest
          docker push ghcr.io/p3rik/tall-stack-db:latest
